<?php
/**
 * @file
 *
 */

/**
 * Implements hook_block_info().
 */
function  easyddb_search_ext_block_info() {
  $blocks['search_ext'] = array(
    'info' => t('Search extension'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function easyddb_search_ext_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'search_ext':
      $block['title'] = t('Search extention pane');
      $block['content'] = drupal_get_form('easyddb_search_ext_form');
      break;
  }

  return $block;
}

/**
 * Form for search extension.
 */
function easyddb_search_ext_form($form, &$form_state) {
  $form = array();

  $reservables = variable_get('ting_reservable_types', _ting_default_reservable_types());
  $options = array();
  // Its needed for correct format of options.
  foreach ($reservables as $k => $v) {
    $options[$v] = $v;
  }
  // Sort alphabetical, ASC.
  asort($options);

  $form['types'] = array(
    '#type' => 'select',
    '#title' => t('Search by type of material:'),
    '#options' => $options,
    '#empty_option' => t('Select a type'),
    '#prefix' => '<div class="select-wrap">',
    '#suffix' => '</div>',
    '#attributes' => array('onchange' => 'form.submit(types)'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#name' => 'search_ext',
    '#value' => t('Search'),
    '#submit' => array('easyddb_search_ext_submit'),
    '#attributes' => array('style' => 'display: none;'),
  );

  $form['#attached']['js'] = array(
    drupal_get_path('module', 'easyddb_search_ext') . '/js/easyddb_search_ext.js',
    drupal_get_path('module', 'ting_search') . '/js/ting_search_overlay.js',
  );

  return $form;
}

/**
 * Submit handler for search extension form.
 */
function easyddb_search_ext_submit($form, &$form_state) {
  $submit = $form_state['triggering_element']['#name'];
  if ($submit == 'search_ext' && isset($form_state['values']['types']) && !empty($form_state['values']['types'])) {
    $type = $form_state['values']['types'];
    drupal_goto("search/ting/facet.type={$type}", array(
      'query' => array(
        'sort' => "date_descending",
        'facets[]' => "facet.type:{$type}",
      )
    ));
  }
}
