<?php
/**
 * @file
 *
 */

/**
 * Implements hook_block_info().
 */
function  easyddb_search_ext_block_info() {
  $blocks['search_ext'] = array(
    'info' => t('Search extension'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function easyddb_search_ext_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'search_ext':
      $block['title'] = t('Search extention pane');
      $block['content'] = drupal_get_form('easyddb_search_ext_form');
      break;
  }

  return $block;
}

/**
 * Form for search extension.
 */
function easyddb_search_ext_form($form, &$form_state) {
  $form = array();

  $reservables = variable_get('ting_reservable_types', _ting_default_reservable_types());
  $options = array();
  // Its needed for correct format of options.
  foreach ($reservables as $k => $v) {
    $options[$v] = $v;
  }
  $form['types'] = array(
    '#type' => 'select',
    '#title' => t('Types'),
    '#options' => $options,
    '#empty_option' => t('-None-')
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#name' => 'search_ext',
    '#value' => t('Search'),
    '#submit' => array('easyddb_search_ext_submit'),
  );

  return $form;
}

/**
 * Submit handler for search extension form.
 */
function easyddb_search_ext_submit($form, &$form_state) {
  $submit = $form_state['triggering_element']['#name'];
  if ($submit == 'search_ext' && isset($form_state['values']['types']) && !empty($form_state['values']['types'])) {
    $type = $form_state['values']['types'];
    drupal_goto("search/ting", array(
      'query' => array(
        'facets[]' => "facet.type:{$type}"
      )
    ));
  }
}
